---
version: "3.8"
services:
  version:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: version
    ports:
      - 8099:8090
    environment:
      - AUTHKEY
    volumes:
      - ./version_db:/data
    restart: unless-stopped