---
version: "3.8"
services:
  version:
    build: 
      context: ./app
      dockerfile: Dockerfile
    container_name: version
    environment:
      - var
    volumes:
      - ./version_db:/data
    restart: unless-stopped